### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by caniko** [yzhsuper/django-scatter#1]
Hey

Would you mind taking a look at mine? I can't get it to work:
https://github.com/caniko2/django-scatter-auth

**Comment by caniko** [comment]
It is the validation function that returns false

**Comment by yzhsuper** [comment]
> It is the validation function that returns false

Sorry, I have a holiday for 3 days

just now i check you code，No problem was found.
I don't understand either.

Finally, i found the 
```
var network = {
      blockchain:'eos',
      protocol:'https',
      host:'nodes.get-scatter.com',
      port:443,
      chainId:'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
    }
```
i replace the host
```
var network = {
        blockchain: 'eos',
        protocol: 'http',
        host: 'api.farmeos.io',
        port: 443,
        chainId: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
    };
```
it's work

**Comment by caniko** [comment]
The problem percists. To reproduce:
1. Signup
2. Logout
3. Autologin -> Fail

Console log:
`Object { success: false, error: "Can't find a user for the provided signature with public key <key>" }`

This is caused by the fact that res can't verify the key. Meaning that the validation protocol is bugged.

Both hosts work in my region

**Comment by yzhsuper** [comment]
1. debug there
```
is_valid = validate_signature(public_key=public_key, shaData=shaData, res=res)
print(is_valid)
```

2. check you scatter desktop version?

**Comment by caniko** [comment]
I got it working :)
